### ISSUE TITLE
Render via system rather than hardcoding

### ISSUE THREAD

**Issue by Reificator** [Reificator/ecs-arcade#5]
- [x] Figure out how to give a Render system access to the canvas context.
- [x] Make a pull request to https://github.com/ayebear/picoes
- [x] Update to https://github.com/ayebear/picoes v0.2.5

# Pending #

- [x] https://github.com/ayebear/picoes/pull/18

**Comment by Reificator** [comment]
Pull request is made, if there's no response on it, then in two weeks the fork should be published instead.  But since it's an active project I expect we'll get some kind of response within that timeframe...

**Comment by ayebear** [comment]
Version 0.2.5 is on npm now:
https://www.npmjs.com/package/picoes

Thanks for your contribution, that's a useful feature I didn't think of before.

**Comment by Reificator** [comment]
@ayebear Thanks, that was quick! 👍

Yeah, I brainstormed a bunch of ways to get ahold of what I needed, and I kept coming back to this as the cleanest option.  Minimal changes and it mirrors the API for component creation.

**Comment by Reificator** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Render via system rather than hardcoding](https://trello.com/c/CM6s8cFK/3-render-via-system-rather-than-hardcoding)
